// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Client$BsSocket = require("bs-socket/src/Client.bs.js");

console.log("Hello, BuckleScript and Reason!");

var Client = Client$BsSocket.Make(/* Message-Repacking */[]);

var client = Curry._1(Client[/* create */0], /* () */0);

Curry._2(Client[/* emit */1], client, "hi from client");

exports.Client = Client;
exports.client = client;
/*  Not a pure module */
